version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
      - "35729:35729"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    command: npm start
    
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0 --reload
