version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "3001:8080"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - REACT_APP_BACKEND_URL=http://localhost:5001
    
  backend:
    build: ./backend
    ports:
      - "5001:8080"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
